# Generated by Django 4.0.5 on 2022-06-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
